language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - travis_retry python setup.py install
  - pip install coveralls

script:
    coverage run --source=betfairlightweight setup.py test

after_success:
  coveralls
